export const SET_TEXT_MESSAGE = 'SET_TEXT_MESSAGE';
export const SET_IMAGE_MESSAGE = 'SET_IMAGE_MESSAGE';
export const SET_SOCKET_CONNECTION = 'SET_SOCKET_CONNECTION';
export const ADD_PERSON_TYPING = 'ADD_PERSON_TYPING';
export const REMOVE_PERSON_TYPING = 'REMOVE_PERSON_TYPING';
