export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_TYPING = 'SET_TYPING';
export const SET_USERNAME_TO_STATE = 'SET_USERNAME_TO_STATE';
export const SET_IS_LOGGED_IN_TO_STATE = 'SET_IS_LOGGED_IN_TO_STATE';
